server:
    port: 8080

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8760/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
    application:
        name: gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            mvc:
                routes:
                    - id: account_route
                      uri: http://localhost:8081
                      predicates:
                      - Path=/account/**
                    